const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc'
    }
  },
  host: 'localhost:3000',
  basePath: '/api/v1',
  apis: ['./routes/*.js']
};

module.exports = swaggerJsdoc(options);
